spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: fechamento_caixa
      authentication-database: admin
      # username: admin
      # password: password
      auto-index-creation: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080
  servlet:
    context-path: /api
  error:
    include-message: always
    include-binding-errors: always

jwt:
  secret: ${JWT_SECRET:your-256-bit-secret}
  expiration: ${JWT_EXPIRATION:86400000} # 24 hours

google:
  drive:
    credentials-file: ${GOOGLE_DRIVE_CREDENTIALS:classpath:credentials.json}
    backup-folder-id: ${GOOGLE_DRIVE_BACKUP_FOLDER:}
    tokens-folder: ${user.home}/.tokens/fechamento-caixa
    application-name: Fechamento de Caixa

logging:
  level:
    root: INFO
    com.controle.fechamentocaixa: DEBUG
    org.springframework.data.mongodb: DEBUG
    org.springframework.security: DEBUG

app:
  backup:
    google-drive:
      credentials-file: credentials.json
      backup-folder-id: your-folder-id-here
  javafx:
    title: Sistema de Fechamento de Caixa
    width: 1024
    height: 768
