spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: fechamento_caixa
      auto-index-creation: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080
  servlet:
    context-path: /
  error:
    include-message: always
    include-binding-errors: always

jwt:
  secret: ${JWT_SECRET:your-256-bit-secret-key-here-minimum-32-chars}
  expiration: 86400000 # 24 hours in milliseconds

google:
  drive:
    credentials-folder: ${user.home}/.credentials/fechamento-caixa
    tokens-folder: ${user.home}/.tokens/fechamento-caixa
    application-name: Fechamento de Caixa
    backup-folder-id: # Add your Google Drive folder ID here

logging:
  level:
    org.springframework.security: INFO
    com.seucodigo.fecharcaixa: DEBUG
