spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: fechamento_caixa
      authentication-database: admin
      # username: admin
      # password: password
      auto-index-creation: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080
  servlet:
    context-path: /api
  error:
    include-message: always
    include-binding-errors: always

jwt:
  secret: ${JWT_SECRET:your-256-bit-secret-key-here}
  expiration: 86400000 # 24 hours in milliseconds

google:
  drive:
    credentials-folder: ${user.home}/.credentials/fechamento-caixa
    tokens-folder: ${user.home}/.tokens/fechamento-caixa
    application-name: Fechamento de Caixa
    backup-folder-id: # Add your Google Drive folder ID here

logging:
  level:
    org.springframework.data.mongodb: INFO
    org.springframework.security: DEBUG
    com.seucodigo.fecharcaixa: DEBUG
    com.controle.fechamentocaixa: DEBUG

app:
  backup:
    google-drive:
      credentials-file: credentials.json
      backup-folder-id: your-folder-id-here
  javafx:
    title: Sistema de Fechamento de Caixa
    width: 1024
    height: 768
