spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/fecharcaixa_test
      auto-index-creation: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 0
  servlet:
    context-path: /api

jwt:
  secret: testSecretKey12345678901234567890testSecretKey
  expiration: 3600000 # 1 hour

google:
  drive:
    credentials-folder: ${java.io.tmpdir}/fecharcaixa-test/credentials
    tokens-folder: ${java.io.tmpdir}/fecharcaixa-test/tokens
    application-name: Fechar Caixa Test
    backup-folder-id: test_folder_id
